In [1]:
#WEEK 13 SESSION 2

# اللي تحت ده describtion

[I 2026-04-05 17:07:43.929 ServerApp] Extension package jupyter_lsp took 0.2346s to import
[I 2026-04-05 17:07:44.259 ServerApp] Extension package jupyter_server_terminals took 0.3276s to import
[I 2026-04-05 17:07:52.116 ServerApp] Extension package panel.io.jupyter_server_extension took 6.3703s to import
[I 2026-04-05 17:07:52.117 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2026-04-05 17:07:52.126 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2026-04-05 17:07:52.138 ServerApp] jupyterlab | extension was successfully linked.
[I 2026-04-05 17:07:52.148 ServerApp] notebook | extension was successfully linked.
[I 2026-04-05 17:07:55.919 ServerApp] notebook_shim | extension was successfully linked.
[I 2026-04-05 17:07:55.920 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2026-04-05 17:07:56.137 ServerApp] notebook_shim | extension was successfully loaded.
[I 2026-04-05 17:07:56.143 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2026-04-05 17:07:56.144 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2026-04-05 17:07:56.173 LabApp] JupyterLab extension loaded from C:\ProgramData\anaconda3\Lib\site-packages\jupyterlab
[I 2026-04-05 17:07:56.174 LabApp] JupyterLab application directory is C:\ProgramData\anaconda3\share\jupyter\lab
[I 2026-04-05 17:07:56.175 LabApp] Extension Manager is 'pypi'.
[I 2026-04-05 17:07:57.162 ServerApp] jupyterlab | extension was successfully loaded.
[I 2026-04-05 17:07:57.185 ServerApp] notebook | extension was successfully loaded.
[I 2026-04-05 17:07:57.186 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2026-04-05 17:07:57.191 ServerApp] Serving notebooks from local directory: C:\Users\Hilti
[I 2026-04-05 17:07:57.192 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2026-04-05 17:07:57.192 ServerApp] http://localhost:8888/tree?token=2e6bbd848430e5356b408e85feee6e3aecb0375405852c9f
[I 2026-04-05 17:07:57.192 ServerApp]     http://127.0.0.1:8888/tree?token=2e6bbd848430e5356b408e85feee6e3aecb0375405852c9f
[I 2026-04-05 17:07:57.193 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2026-04-05 17:07:57.305 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/Hilti/AppData/Roaming/jupyter/runtime/jpserver-628-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=2e6bbd848430e5356b408e85feee6e3aecb0375405852c9f
        http://127.0.0.1:8888/tree?token=2e6bbd848430e5356b408e85feee6e3aecb0375405852c9f
[I 2026-04-05 17:07:57.709 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2026-04-05 17:08:38.329 ServerApp] 400 GET /api/contents/Desktop/Microsoft%20OneDrive.lnk?type=file&content=1&hash=1&format=text&contentProviderId=undefined&1775401718289 (::1): C:\Users\Hilti\Desktop\Microsoft OneDrive.lnk is not UTF-8 encoded
[W 2026-04-05 17:08:38.330 ServerApp] wrote error: 'C:\\Users\\Hilti\\Desktop\\Microsoft OneDrive.lnk is not UTF-8 encoded'
    Traceback (most recent call last):
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\fileio.py", line 562, in _read_file
        (bcontent.decode("utf8"), "text", bcontent)
         ~~~~~~~~~~~~~~~^^^^^^^^
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 12: invalid start byte

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\handlers.py", line 156, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
        ...<7 lines>...
        )
        ^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 197, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 926, in get
        model = await self._file_model(
                ^^^^^^^^^^^^^^^^^^^^^^^
            path, content=content, format=format, require_hash=require_hash
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 835, in _file_model
        content, format, bytes_content = await self._read_file(os_path, format, raw=True)  # type: ignore[misc]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\fileio.py", line 571, in _read_file
        raise HTTPError(
        ...<3 lines>...
        ) from e
    tornado.web.HTTPError: HTTP 400: bad format (C:\Users\Hilti\Desktop\Microsoft OneDrive.lnk is not UTF-8 encoded)
[W 2026-04-05 17:08:38.409 ServerApp] 400 GET /api/contents/Desktop/Microsoft%20OneDrive.lnk?type=file&content=1&hash=1&format=text&contentProviderId=undefined&1775401718289 (f1693abca9124a7daa4b6616b64c15e0@::1) 90.75ms referer=http://localhost:8888/tree/Desktop
[W 2026-04-05 17:08:38.412 ServerApp] 400 GET /api/contents/Desktop/Microsoft%20OneDrive.lnk?type=file&content=1&hash=1&format=text&contentProviderId=undefined&1775401718304 (::1): C:\Users\Hilti\Desktop\Microsoft OneDrive.lnk is not UTF-8 encoded
[W 2026-04-05 17:08:38.413 ServerApp] wrote error: 'C:\\Users\\Hilti\\Desktop\\Microsoft OneDrive.lnk is not UTF-8 encoded'
    Traceback (most recent call last):
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\fileio.py", line 562, in _read_file
        (bcontent.decode("utf8"), "text", bcontent)
         ~~~~~~~~~~~~~~~^^^^^^^^
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 12: invalid start byte

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\handlers.py", line 156, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
        ...<7 lines>...
        )
        ^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 197, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 926, in get
        model = await self._file_model(
                ^^^^^^^^^^^^^^^^^^^^^^^
            path, content=content, format=format, require_hash=require_hash
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 835, in _file_model
        content, format, bytes_content = await self._read_file(os_path, format, raw=True)  # type: ignore[misc]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\fileio.py", line 571, in _read_file
        raise HTTPError(
        ...<3 lines>...
        ) from e
    tornado.web.HTTPError: HTTP 400: bad format (C:\Users\Hilti\Desktop\Microsoft OneDrive.lnk is not UTF-8 encoded)
[W 2026-04-05 17:08:38.418 ServerApp] 400 GET /api/contents/Desktop/Microsoft%20OneDrive.lnk?type=file&content=1&hash=1&format=text&contentProviderId=undefined&1775401718304 (f1693abca9124a7daa4b6616b64c15e0@::1) 93.96ms referer=http://localhost:8888/tree/Desktop
[W 2026-04-05 17:20:47.411 ServerApp] 404 GET /api/contents/D%3A%5CAHMED?content=0&hash=0&1775402447406 (::1): D:\AHMED is not a relative API path
[W 2026-04-05 17:20:47.411 ServerApp] wrote error: 'D:\\AHMED is not a relative API path'
    Traceback (most recent call last):
      File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\auth\decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\handlers.py", line 148, in get
        if not cm.allow_hidden and await ensure_async(cm.is_hidden(path)):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 197, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\filemanager.py", line 1090, in is_hidden
        os_path = self._get_os_path(path=path)
      File "C:\ProgramData\anaconda3\Lib\site-packages\jupyter_server\services\contents\fileio.py", line 298, in _get_os_path
        raise HTTPError(404, "%s is not a relative API path" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (D:\AHMED is not a relative API path)
[W 2026-04-05 17:20:47.419 ServerApp] 404 GET /api/contents/D%3A%5CAHMED?content=0&hash=0&1775402447406 (f1693abca9124a7daa4b6616b64c15e0@::1) 9.85ms referer=http://localhost:8888/tree/Desktop
[I 2026-04-05 17:24:34.254 ServerApp] Creating new notebook in /Desktop
[I 2026-04-05 17:24:34.321 ServerApp] Writing notebook-signing key to C:\Users\Hilti\AppData\Roaming\jupyter\notebook_secret
[I 2026-04-05 17:24:35.366 ServerApp] Saving file at /Desktop/Untitled.ipynb
[I 2026-04-05 17:24:35.461 ServerApp] Kernel started: 39af2f96-0cbd-481e-9d97-78bcd04198d4
[I 2026-04-05 17:24:38.486 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:24:38.500 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[W 2026-04-05 17:24:38.515 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[I 2026-04-05 17:24:38.527 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:24:38.556 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:24:38.567 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[W 2026-04-05 17:24:38.643 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x000001BA28D725D0>
[W 2026-04-05 17:24:38.689 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x000001BA27CE3750>
[I 2026-04-05 17:25:03.754 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:25:16.247 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:25:25.907 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:25:31.953 ServerApp] Kernel started: 68efe986-f3d1-414b-9b81-e96dfaefa315
[I 2026-04-05 17:25:33.506 ServerApp] Connecting to kernel 68efe986-f3d1-414b-9b81-e96dfaefa315.
[I 2026-04-05 17:27:26.532 ServerApp] Saving file at /Desktop/Week 13 S 2.ipynb
[I 2026-04-05 17:31:28.552 ServerApp] Saving file at /Desktop/Week 13 S 2.ipynb
[I 2026-04-05 17:37:30.555 ServerApp] Saving file at /Desktop/Week 13 S 2.ipynb
[W 2026-04-05 17:37:48.447 LabApp] Could not determine jupyterlab build status without nodejs
[I 2026-04-05 17:37:48.556 ServerApp] Connecting to kernel 39af2f96-0cbd-481e-9d97-78bcd04198d4.
[I 2026-04-05 17:37:48.588 ServerApp] Connecting to kernel 68efe986-f3d1-414b-9b81-e96dfaefa315.
[I 2026-04-05 17:47:34.510 ServerApp] Saving file at /Desktop/Week 13 S 2.ipynb
[I 2026-04-05 17:49:35.522 ServerApp] Saving file at /Desktop/Week 13 S 2.ipynb

# Variables

In [2]:
x =13 #  هنا بقوله الاكس تساوي قيمه كذا 

In [3]:
x

13

In [4]:
    X #دي معموله قصد علشان اعرف الايرور  لان بايثون حساسه جدا فا لازم تفرق انت كاتب ايه في تعريف الفاريبل كاتبه كابيتل ولا سمول 

NameError: name 'X' is not defined

In [ ]:
x+2 
# هنا بقوله اجمع 2 علي قيمة الفاريبل اللي هي 13 يبقى اكس +2 تساوي 15

In [ ]:
y=x+2
# هنا بقوله الفاريبل اللي هو اكس+ 2 عرفه كا فاريبل واي او عايز اقوله بطريقه تانيه ان الواي بتساوي اكس و ضيف عليها 2

In [ ]:
y*2 
#  هنا بقوله اضرب الواي في اتنين الاسترسك* دي علامة الضرب 

In [ ]:
v1=9
v2=2.5
v3="depi"
v4=True
v5='ahmed'

In [ ]:
print(type(v1)) 
#v1 هنا بقوله اطبعلي او قولي ايه الداتا تايب بتاع الفاريبل

In [ ]:
print(type(v2))
#هنا بقوله اطبعلي او قولي ايه الداتا تايب بتاع الفاريبل

In [ ]:
print(type(v3)) 
#هنا بقوله اطبعلي او قولي ايه الداتا تايب بتاع الفاريبل

In [ ]:
print(type(v4))
#هنا بقوله اطبعلي او قولي ايه الداتا تايب بتاع الفاريبل

In [ ]:
V_str = str(v1)
# V_strهنا بقوله غير الداتا تايب بتاع الفاريبل و سميه و 
#او بقوله الفاريبل V_str هو الفاريبل بعد ما غيرت نوع الدتا بتاعه لاسترنج
V_str

In [ ]:

print(type(V_str))
# هنا بقوله اطبع الداتا تايب 

In [ ]:
v_int=int(v2)
# هنا الفاريبل غيرت النوع بتاعه لانتجر 
# v2=2.5 بس خلي بالك الانتجر بتقرا الارقام الصحيحه بس فا هتقرا الرقم 2 بس فا مش هتقرا ان الفاريبل 

In [ ]:
v_int   # هنا بقوله الفاريبل ده يساوي ايه

In [ ]:
print(type(v_int))
    # هنا يقول الداتا تايب فرق بين قيمة الفاريبل اوىاللي جوه وبين الداتا تايب بتاعته 

In [ ]:
print("My Name Is",v5)
# هنا بقوله اطبع قيمة الفاريبل اللي هو في 5 و حط قبله الجمله دي بس لالزم بين دابل كوتيشن علشان بس يعرف ان دي تكست عادي مش فاريبل جواه قيمة او 

In [ ]:
print("My Name Is",v5, "&","my gpa",v2
     )
#  هنلىا ع8ايز اطبع كذا حاجه فا بفصل بينهم بفصله عاديه ,

In [ ]:
print("My Name is", v5, " My Grade is", v1,"My GPA = ", v2, "Scholarship", v3)
# printنفس فكرت اللي فاتت انايس عايز اطبع كذا حاجه ورا بعض بدل ما  اقعد كل  شويه اكتب 

# Next step is very importanat 

In [ ]:
print(f"My Name is {v5} My Grade is {v1} My GPA = {v2} Scholarship {v3}")
#  طب انا عايز اطبع شوية حاجات بس خاسف انسى فصله او" اعمل ايه
#  اللي هي بحط اف فورمات قبل الكود علشان اقوله احفظ الفورمات و كمان الاقواس الكيرلي دي علشان يفهم اني بنده علي الفاريبل بتاعي f-string هنستخدم 

In [ ]:
# Arithmetic Operators
a = 15 
b = 4

print("=== Arithmetic Operators ===") # هنا اطبع الكلمه دي
print(f"Addition: {a} + {b} = {a + b}") #الجمع او الاضافه 
print(f"Subtraction: {a} - {b} = {a - b}")# الجزء اللي عد اللي يساوي ده هو الناتج لان اللي قبل اللي يساوي بقوله اطبع الفاريبل الاول - الفاريبل الثاني اللي هي المعادله الجزء الثاني ده بقوله طلع ناتج الطرح
print(f"Multiplication: {a} * {b} = {a * b}")# الضرب 
print(f"Division: {a} / {b} = {a / b}")          # Returns float (3.75) القسمه دي 
print(f"Floor Division: {a} // {b} = {a // b}")  # Returns integer (3)
print(f"Modulus: {a} % {b} = {a % b}")           # Remainder (3)   اتبقى كام يعني 
print(f"Exponentiation: {a} ** {b} = {a ** b}")  # Power (15^4) الدابل استريسك يعني البور او الاس بالعاميه 

In [ ]:
grade = input("please input your grade") #  هنا تدوس shift + enter 
#  هنا  معناها انك هتاخد رقم او فاليو من الكلاينت input هنا

In [ ]:
type(grade)

In [ ]:
grade = int(input("please input your grade")) # هنا غيرنا نوع الداتا علشان اقدر اجمع و اطرح 

In [ ]:
grade+2


# اللي جاي ده سوال مهم 

In [ ]:
#Question: Write a Python program that asks the user to enter a total number of days. The program should convert this input into the equivalent number of Years, Weeks, and Remaining Days.

In [ ]:
# Step 1: Get input from the user
total_days = int(input("Enter the number of days: ")) 

# Step 2: Calculate years using Integer Division (//)
# We use // to get the whole number of years
years = total_days // 365     # 375//365 = 1

# Step 3: Find remaining days after taking out the years using Remainder (%) الباقي 
remaining_days_after_years = total_days % 365   # 375%365 = 10

# Step 4: Calculate weeks from the remaining days
weeks = remaining_days_after_years // 7   # 10//7 = 1

# Step 5: Find the final remaining days using Remainder (%)
days = remaining_days_after_years % 7   # 10% 7 = 3
# Step 6: Print the result هنا بقوله اللي طلعه من الحسابات دي ايه 
print(f"\nResults for {total_days} days:")
print(f"Years: {years}")
print(f"Weeks: {weeks}")
print(f"Days: {days}")

In [ ]:
#Comparison Operators  المقارنات 
a = 10
b = 5
# دي bool  تطلع صح و خطئ 
print("\n=== Comparison Operators ===")
print(f"{a} > {b}: {a > b}")
print(f"{a} < {b}: {a < b}") 
print(f"{a} == {b}: {a == b}")#هل تساوي ولا لا ده زي اكنه بيشوف الشرط اتقق او لا 
print(f"{a} != {b}: {a != b}") # هنا معناها لا تساوي 
print(f"{a} >= {b}: {a >= b}") 
print(f"{a} <= {b}: {a <= b}")

In [ ]:
# Logical Operators المنطقيه 
print("\n=== Logical Operators ===")
x = True
y = False

print(f"{x} and {y}: {x and y}") # الشرطين يتحققو
print(f"{x} or {y}: {x or y}")# سرط من الاثنين يتحقق 
print(f"not {x}: {not x}") # عكس القيمة

Write a Python program that prompts the user to enter the Length and Width of a rectangle. The program should calculate and display:

1-The Area (Length × Width). قانو المساحه 

2-The Perimeter (2 × (Length + Width)). المحيط 

In [ ]:
l=float(input("Enter the length:"))# فلوتى علشان ممكن يكون في كسور عادي 
w=float(input("Enter the width:"))
area=l*w
perimeter=2*(l+w)
print(f'area={area}\nperimeter={perimeter}') # خلي بالكمن سلاش ان علشان يبقى في سطرين مش سطر واحد 

## حل الدكتور للسوال اللي فات الفرق بس ان الدكتور كاتبه تفاصيل 

In [ ]:
# 1. Get user input for length and width
# We use float() to allow decimal values for dimensions
length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

# 2. Calculate Area and Perimeter
# Area formula: Length * Width
area = length * width
# Perimeter formula: 2 * (Length + Width)
perimeter = 2 * (length + width)
# 3. Create a formatted report
print(f"\n--- Rectangle Results ---")
print(f"Length: {length} | Width: {width}")
print(f"The Area is: {area:.2f}")
print(f"The Perimeter is: {perimeter:.2f}")
#2f يعني اظهر اول رقمين  بعد العلامه بس كده 
# 4. Using 'pass' if we want to add future checks 
if length == width: 
    print("Note: This rectangle is a square!")
else:
    # No special note needed for non-square rectangles
    pass

# 1.4 String Operations



Strings are crucial for data science - column names, text data, reports, etc.

In [ ]:
# String Creation and Basic Operations
first_name = "Amal"
last_name = 'Mahmoud'
age = 30

In [ ]:
# String Concatenation
full_name = first_name + " " + last_name # هنا بجمع الباسماء او الكلمات باستخدام +
print(f"Full Name: {full_name}")

In [ ]:
print("\tProgramming Language") #\t is Tab In Keybord
print("="*150) # هنا يفهم انه يطبع يساوي دي 150 مره ورا بعض 
print("1-python \n2-SQL \n3-C#") #\n is new line

In [ ]:
# String Methods
text = "  Data Analysis with Python  "

print(f"Original: '{text}'") #  النص الاصلي 
print(f"Upper: '{text.upper()}'") #كل الحروف كابتل 
print(f"Lower: '{text.lower()}'") #  كل الحرووف سمول
print(f"title: '{text.title()}'")# اول حرف بس اللي كابتل من الكلمه
print(f"Strip: '{text.strip()}'") # strip is trim in excel  تشيل كل المسافات اللي ملهاش لازمه زياده
print(f"capitalize: '{text.capitalize()}'") #   تخلي اول حرف من الجمله كلها كابيتال 
print(f"Replace: '{text.replace('Python', 'R')}'")
print(f"Split: {text.strip().split(' ')}")

In [ ]:
# -4 -3 -2 -1  <- الفهرسة العكسية (من اليمين لليسار)
Name = "AMAL"
#  0  1  2  3  <- الفهرسة العادية (من اليسار لليمين)

print(Name[3])# FIRST SOLUTION
print(Name[-1]) #2nd solution

In [ ]:
print(Name[2]) #1
print(Name[-2])#2

In [ ]:
# String Indexing and Slicing
course = "Python for Data Analysis"

print(f"\nString: '{course}'")
print(f"First character: '{course[0]}'")
print(f"Last character: '{course[-1]}'")
print(f"First 6 characters: '{course[0:6]}'")
print(f"Every 2nd character: '{course[::2]}'")
print(f"Reverse: '{course[::-1]}'")

In [ ]:
#  طب افرض عايز اقطع شوية حروف او كلمه اللي جايه دي بقى توريك 

In [ ]:
print(f"First 6 characters: '{course[0:6]}'")

In [ ]:
print(f"First 6 characters: '{course[11:15]}'")

In [ ]:
print(f"First 6 characters: '{course[-8:]}'") # دي مهمه جدا جدا لان العد عكسييييييييي

In [ ]:
print(f"First 6 characters: '{course[:6]}'")

In [ ]:
print(f"Every 2nd character: '{course[::2]}'")

## Exercise 1.1: Variables and Strings

Create variables for a student's information (name, age, grade, GPA) and use string formatting to create a report card message. Then, extract and display the student's initials from their full name.

In [ ]:
# Exercise 1.1 - Your Solution Here
# TODO: Create variables for student information
# TODO: Create a formatted report card message
# TODO: Extract and display initials

In [ ]:
# 1. Create variables for student information
first_name= "Ahmed"
last_name= "Fathy"
Full_Name= first_name+""+last_name
student_id = "3818578"
math_score = 95
science_score = 92
english_score = 98
avg = ( math_score + science_score + english_score)/3

print(f'------ Student Report Card --------- ')
print(f'Student_name: {Full_Name} \nstudent_id :{student_id}' )
print('-'*30)
print(f'math : {math_score}\nscience: {science_score}\nenglish: {english_score}')
print('-'*30)
print(f'AVg : {avg}')
print('-'*30)
print(f'student_intialize {first_name[0]}{last_name[0]}')

# Week 14 session 1 

## Data Structures 

### List 

In [ ]:
# creating lists 
numbers=[1, 9, 3, 4, 5]
fruits =["apple","banana","cherry"]
mixed=[1,"hello",3.14,True]
print(f"numbers: {numbers}")
print(f"fruit:{fruits}")
print(f"mixed:{mixed}")

In [ ]:
fruits

In [ ]:
#accessing elements (indxing)
print(f"\nFirst fruit:{fruits[0]}")
print(f"\nlast fruit:{fruits[-1]}")
print(f"\n2nd fruit:{fruits[1:3]}")
print(f"\n2nd fruit:{fruits[1]}")

In [ ]:
#modifying lists (mutable)
fruits[1]= "blueberry"
fruits[-1]= "Mango"
fruits
#print(f"\n2nd fruit:{fruits[1]}")
#print(f"\nlast fruit:{fruits[-1]}")

In [ ]:
fruits.append("orange")
fruits

In [ ]:
#list methods
print("\n==== list methods ===")
data=[10,20,30]
data
#Addint elemint
data.append(40)  #add to end 
print(f"after append(40): {data}")

In [ ]:
data.insert(1,15) #insert at index 1
print(f"After insert:{data}")

In [ ]:
data.extend([50,60]) #add multiple elements
print(f"After extend:{data}")

In [ ]:
#remove elements 
poped =data.pop() #remove and return last element
print(f"poped :{poped}, list{data}")

In [ ]:
data.remove(15) #remove value
print(f"After remove 15 :{data}")

In [ ]:
# Other useful methods
numbers = [3, 1, 4, 1, 5, 9, 2, 6]
print(f"\nOriginal: {numbers}")
numbers.sort()  # Sort in place
print(f"Sorted: {numbers}")
print(max(numbers))
print(min(numbers))
print(sum(numbers))
numbers[::-1]

In [ ]:
numbers.reverse()  # Reverse in place
print(f"Reversed: {numbers}")

# Output:
# Reversed: [9, 6, 5, 4, 3, 2, 1, 1]

print(f"Count of 1: {numbers.count(1)}")

# Output:
# Count of 1: 2

## 3.2 Tuples
Tuples are ordered, immutable collections. Once created, you cannot change their elements. Useful for fixed data.

In [ ]:


# Creating Tuples
coordinates = (10.5, 20.3)
person = ("John", 30, "Engineer")
single_element = (42,) # Note the comma!
print(type(person))

In [ ]:
print(f"Coordinates: {coordinates}")
print(f"Person: {person}")
print(f"Person: {single_element}")

In [ ]:
# Accessing Elements (same as lists)
print(f"\nName: {person[0]}")
print(f"Age: {person[1]}")

In [ ]:
# Tuples are Immutable - This will cause an error: هنا عملنا علشان تعرف انها مش بتقبل التعديل
person[1] = 31  # TypeError!

In [ ]:
# Tuples are Immutable - This will cause an error:
person[1] = 31  # TypeError!
#person.append("Amal")

In [ ]:
# Tuple Unpacking - Very useful!
first_name, age, job = person
print(f"\nUnpacked - Name: {first_name}, Age: {age}, Profession: {job}")

In [ ]:
# Multiple Return Values using Tuples
def get_statistics(numbers):
    return min(numbers), max(numbers), sum(numbers)/len(numbers)

data = [10, 20, 30, 40, 50]
minimum, maximum, average = get_statistics(data)
print(f"\nData: {data}")
print(f"Min: {minimum}, Max: {maximum}, Avg: {average}")

# 3.3 Dictionaries دي خليها اخر حاجه في السيشن علشان صعبه 
Dictionaries store key-value pairs. Extremely important for data science - similar to JSON, pandas DataFrames use dictionary-like structure.


In [ ]:
# Creating Dictionaries
student = {
    "name": ["Amr", "Eslam", "Mohaned", "Salma", "Ann"],
    "age": [22, 21, 24, 20, 19],
    "major": ["Data Science", "Data Analysis", "Data Science", "Data Analysis", "Data Analysis"],
    "gpa": [3.8, 3.5, 3.7, 3.8, 3.4]
}

print("Student Information:")
print(student)



In [ ]:
# دي مهمه علشان الباندس
import pandas as pd
# Creating Dictionaries
student = {
    "name": ["Amr", "Eslam", "Mohaned", "Salma", "Ann"],
    "age": [22, 21, 24, 20, 19],
    "major": ["Data Science", "Data Analysis", "Data Science", "Data Analysis", "Data Analysis"],
    "gpa": [3.8, 3.5, 3.7, 3.8, 3.4]
}

print("Student Information:")
print(student)
df = pd.DataFrame(student)
df

##### =======================================================

In [ ]:
depi = {
    "name": "Omar",
    "age": 20,
    "GPA": 3.8
}
depi

In [ ]:
# Adding/Modifying Entries
student['email'] = ['Amr@university.edu', 'Eslam@university.edu', 'Mohaned@university.edu', 'Salma@university.edu', 'Ann@university.edu']
student['age'] = [27, 21, 20, 20, 18] # Modify existing key
print(f"\nUpdated: {student}")

In [ ]:
# Dictionary Methods
print("\n=== Dictionary Methods ===")
print(f"Keys: {student.keys()}")

In [ ]:
# Dictionary Methods
print("\n=== Dictionary Methods ===")
print(f"values: {student.values()}")

In [ ]:

print(f"items: {student.items()}")

## 3.4 Sets
Sets are unordered collections of unique elements. Perfect for removing duplicates and set operations.

In [ ]:
# Creating Sets
fruits = {"apple", "banana", "cherry", "banana", "banana"}
numbers = {1, 2, 3, 4, 5}
print(type(fruits))
fruits

In [ ]:
# Sets automatically remove duplicates
duplicate_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
unique_numbers = set(duplicate_list)
print(f"Original list: {duplicate_list}")
print(f"Unique set: {unique_numbers}")

In [ ]:
# Set Operations
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}


In [ ]:
print(f"\nSet A: {set_a}")
print(f"Set B: {set_b}")

print(f"Union (A | B): {set_a | set_b}")  # All elements
print(f"Intersection (A & B): {set_a & set_b}")  # Common elements
print(f"Difference (A - B): {set_a - set_b}")  # In A but not in B
print(f"Symmetric Difference (A ^ B): {set_a ^ set_b}")  # In A or B, but not both

## MODULE 2: Control Flow

2.1 Conditional Statements (if, elif, else)
Conditional statements allow your program to make decisions and execute different code based on conditions. Essential for data filtering, validation, and categorization in data science."

In [ ]:
grade = 18
if grade >= 10:
  print("pass")

In [ ]:
grade = 8
if grade >= 10:
  print("pass")
else: print("Fail")

In [ ]:
number = int(input("Enter your Grade"))
mean = 8
std = 2

if number < mean - 3 * std or number > mean + 3 * std :
    print("Outlier")
else:
    print("normal")

In [ ]:
group = ["Amr", "Fatma", "Shimaa"]
name = input("Enter Your name: ")

if name.title() in group:
    print("you are in our group")
else:
    print("Out our group")

In [ ]:
# Basic if Statement
temperature = 28

if temperature > 25:
    print(f"Temperature is {temperature}°C - It's hot!")

In [ ]:
# if-else Statement
age = 17

if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")

In [ ]:
number = int(input("Enter your Grade"))
mean = 8
std = 2
if ((number - mean) / std) > 3 or ((number - mean) / std) < -3:
    print("outlier")
else:
    print("normal")

##### حل اخر

In [ ]:
number = int(input("Enter your Grade"))
mean = 8
std = 2
if number < mean - 3 * std or number > mean + 3 * std:
    print("The grade is an outlier")
else:
    print("The grade is normal")

In [ ]:
group = ["Omar", "Mohamed", "Mazen", "Ahmed"]
user = input("Enter your name: ")

if user in group:
    print(f"you are part of the group!")
else:
    print(f"you are not part of the group!")


## حل الدكتور 

In [ ]:
group = ["Amr", "Fatma", "Shimaa"]
name = input("Enter Your name")

if name.title() in  group:
    print ("you are in our group")
else:
    print ("Out our group")
     # .title واحدعن طريق typeخلي بالك هنا و انت بتدخل الاسم الحروف الكابيتال و اللي سمول بتفرق طب و الحل ان كلها تتحول ل 
    # بحيث تخلي اول حرف من الكلمات كلها تبقى كابيتال 
    

In [ ]:
number = int(input("Enter a number: "))
if number % 2 == 0:
    print(f"{number} is even")
else:
    print(f"{number} is odd")

In [ ]:
# if-elif-else Statement (Multiple Conditions)
score = 61

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"

print(f"Score: {score}, Grade: {grade}")

## حل احمد 

In [ ]:
first_number = int(input("enter first number: "))
operation_type = input("enter operation type (+, -, *, /): ")
second_number = int(input("enter second number: "))

if operation_type == "+":
    print(first_number, '+', second_number, '=', first_number + second_number)
elif operation_type == "-":
    print(first_number, '-', second_number, '=', first_number - second_number)
elif operation_type == "*":
    print(first_number, '*', second_number, '=', first_number * second_number)
elif operation_type == "/":
    print(first_number, '/', second_number, '=', first_number / second_number)
else:
    print("invalid operator")

In [ ]:
# Nested Conditionals
income = 50000
has_dependents = True

if income < 30000:
    tax_rate = 0.10
elif income < 70000:
    if has_dependents:
        tax_rate = 0.15
    else:
        tax_rate = 0.20
else:
    tax_rate = 0.25
print(f"Income: ${income}, Tax Rate: {tax_rate*100}%")

# Week 14 Session 2

#### 2.2 Loops - for Loop
Loops allow you to repeat code multiple times. The for loop iterates over sequences (lists, strings, ranges)

In [ ]:
names = ["Ahmed", "Asmaa", "Carol", "Omar"]
print(names[0])
for i in names :
    print(i)

In [ ]:
N1 = "Amal"
for i in N1:
    print(i)

In [ ]:
# For Loop with Range
print("Counting from 1 to 5:")
for i in range(1, 6):  # range(start, stop) - stop is exclusive
    print(i, end=" ")

In [ ]:
for i in range(10):
    print(i)

In [ ]:
# For Loop with List
print("\n\nData Science Tools:")
tools = ["Python", "R", "SQL", "Tableau", "Excel"]
for tool in tools:
    print(f"- {tool}")

In [ ]:
# For Loop with String
print("\nIterating through string:")
word = "DATA"
for letter in word:
    print(letter, end="-")

In [ ]:
# Enumerate - Get Index and Value
print("\n\nEnumerated List:")
fruits = ["Apple", "Banana", "Cherry"]
for index, fruit in enumerate(fruits, start=1):
    print(f"{index}. {fruit}")

In [ ]:
names = ['Ahmed', 'Asmaa', 'Rawan', 'Jomana', 'Yasmeen', 'Ali', 'Mostafa', 'Omar', 'Layla', 'Ziad']

n = input("Enter your name: ")
found = False

for name in names:
    if n.strip().title() == name:
        print(f"Welcome {name}, You're here!")
        found = True
        break

if not found:
    print("Sorry, You're not here")

In [ ]:
gender = ["Male", "male", "M", "Female", "female", "F"]

modify_gender = []

for i in gender:
    if i == "Male" or i == "male" or i == "M":
        modify_gender.append("Male")
    else:
        modify_gender.append("Female")

print(modify_gender)

In [ ]:
numbers = [2, 6, 7, 9, 8, 5, 13, 15, 6, 21]
odd_numbers = []
even_numbers = []

for num in numbers:
    if num % 2 == 0:
        even_numbers.append(num)
    else:
        odd_numbers.append(num)

print(f"Even numbers: {even_numbers}")
print(f"Odd numbers: {odd_numbers}")

### حل  الدكتور 

In [ ]:
num = [5, 8, 12, 4, 9, 7, 6, 3]
even = []
odd = []

for i in num:
    if i % 2 == 0:
        even.append(i)
    else:
        odd.append(i)

print(f" even:{even}\n odd:{odd}")

In [ ]:
# Range with Step
print("\nEven numbers from 0 to 10:")
for num in range(0, 11, 2):  # range(start, stop, step)
    print(num, end=" ")

# 2.3 While Loop
The while loop repeats code as long as a condition is True. Useful for data processing until a condition is met.

In [ ]:
# Basic While Loop
count = 1
print("Counting with while loop:")
while count <= 5:
    print(count, end=" ")
    count += 1 # Increment counter

In [ ]:
# While Loop with Break
print("\n\nSearching for target value:")
numbers = [10, 20, 30, 40, 50]
target = 30
index = 0

while index < len(numbers):
    if numbers[index] == target:
        print(f"Found {target} at index {index}")
        break  # Exit the loop
    index += 1

In [ ]:
guess = 5

while True:
    num = int(input("Enter number between 1-10: "))
    
    if num == guess:
        print("Congratulation ")
        break
    else:
        print("Try again ")

In [ ]:
# While Loop with Continue
print("\nPrinting odd numbers only:")
num = 0
while num < 10:
    num += 1
    if num % 2 == 0:  # If even number
        continue  # Skip to next iteration
    print(num, end=" ")

# Week 16 Session 1

In [ ]:
data = [10, 12, None, 15, 200, 14, None, 11, 13, 300, 10, None, 12]
for i in data:
    if i == None:
        data.remove(i)
print(data)

#### حل الدكتور 

In [ ]:
data = [10, 12, None, 15, 200, 14, None, 11, 13, 300, 10, None, 12]

# ============================
# Step 1: Get values only (no None)
# ============================

clean_data = []
for value in data:
    if value is not None:
        clean_data.append(value)

print(clean_data)

In [ ]:
clean_data = [10, 12, 15, 200, 14, 11, 13, 300, 10, 12]

mean = sum(clean_data) / len(clean_data)

print(f"The mean is: {mean}")

In [ ]:
# ============================
# Step 2: Calculate mean (average)
# ============================

total = 0
for value in clean_data:
    total = total + value

mean = total / len(clean_data)
print("Mean:", mean)

In [ ]:
# ============================
# Step 3: Fill None with mean
# ============================

filled_data = []
for value in data:
    if value is None:
        filled_data.append(mean)  # replace None with mean
    else:
        filled_data.append(value)

print("After filling None:", filled_data)

In [ ]:
# ============================
# Step 4: Calculate IQR for capping
# ============================

sorted_data = sorted(clean_data)

# Q1 = value at 25%      Q3 = value at 75%
q1 = sorted_data[len(sorted_data) // 4] # --> sorted_data[2] = 15
q3 = sorted_data[(len(sorted_data) * 3) // 4]
iqr = q3 - q1
lower_cap = q1 - 1.5 * iqr    # minimum allowed value
upper_cap = q3 + 1.5 * iqr    # maximum allowed value

print("Lower cap:", lower_cap)
print("Upper cap:", upper_cap)

In [ ]:
# ============================
# Step 5: Cap the outliers
# ============================

final_data = []
for value in final_data:
    if value > upper_cap:
        final_data.append(upper_cap)    # too high -> bring it down
    elif value < lower_cap:
        final_data.append(lower_cap)    # too low -> bring it up
    else:
        final_data.append(value)        # normal -> keep it

print("Final data:", final_data)

## 2.4 List Comprehensions
List comprehensions provide a concise way to create lists. Very popular in data science for data transformation.

In [ ]:
# Traditional Way - Creating squares of numbers
squares_traditional = []
for i in range(1, 6):
    squares_traditional.append(i ** 2)
print(f"Traditional: {squares_traditional}")

In [ ]:
# List Comprehension Way - More Pythonic!
squares_comprehension = [i ** 2 for i in range(1, 6)]
print(f"Comprehension: {squares_comprehension}")

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for num in numbers:
    if num % 2 == 0:
        print(num)

In [ ]:
# With Condition - Filter even numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [num for num in numbers if num % 2 == 0]
print(f"\nEven numbers: {even_numbers}")

In [ ]:
# With if-else
numbers = [1, 2, 3, 4, 5, 6]
labels = ["even" if num % 2 == 0 else "odd" for num in numbers]
print(f"\nNumbers: {numbers}")
print(f"Labels: {labels}")

In [ ]:
car = [100000, 200000, 500000, 1200000, 3000000, 1400000]

# ==========================================
# Step 4: Calculate IQR for capping
# ==========================================

sorted_data = sorted(car)

# Q1 = value at 25%      Q3 = value at 75%
q1 = sorted_data[len(sorted_data) // 4] 
q3 = sorted_data[(len(sorted_data) * 3) // 4]

iqr = q3 - q1

lower_cap = q1 - 1.5 * iqr    # minimum allowed value
upper_cap = q3 + 1.5 * iqr    # maximum allowed value
print("Lower cap:", lower_cap)
print("Upper cap:", upper_cap)

In [ ]:
def outlier(clean_data):
    # ==========================================
    # Step 4: Calculate IQR for capping
    # ==========================================
    
    sorted_data = sorted(clean_data)
    
    # Q1 = value at 25%      Q3 = value at 75%
    q1 = sorted_data[len(sorted_data) // 4] #--> sorted_data[2]=15
    q3 = sorted_data[(len(sorted_data) * 3) // 4]
    
    iqr = q3 - q1
    
    lower_cap = q1 - 1.5 * iqr    # minimum allowed value
    upper_cap = q3 + 1.5 * iqr    # maximum allowed value
    print("Lower cap:", lower_cap)
    print("Upper cap:", upper_cap)

In [ ]:
outlier(car) #  هنا بدل ما اعمل لكل حاجه كود لا  هو كود و احد و اقوله اسم الجدول او البيانات وهو يروح يطلع منها الاوتلاير

In [ ]:
def total (x1,x2):
    res = x1+x2
    print(res)

In [ ]:
total(9,345)

In [ ]:
def welcome():
    print("*"*20)
    print("Welcome in DEPI")
    print("*"*20)

In [ ]:
welcome()

In [ ]:
def total (x1,x2):
    res = x1+x2
    return(res)

In [ ]:
total(295,757)

# Functions

"Functions are reusable blocks of code that perform specific tasks. Essential for organizing code, avoiding repetition, and building complex data science workflows."

In [ ]:
# Basic Function Definition
def greet(name):
    """Simple greeting function"""
    return f"Hello, {name}!"

message = greet("Amr")
print(message)

In [ ]:
help(greet) #  هنا هيقولك معادلة جريت دي بتعمل ايه 

In [ ]:
help(len)

In [ ]:
help(input)

In [ ]:
# Function with Multiple Parameters
def calculate_bmi(weight_kg, height_m):
    """
    Calculate Body Mass Index (BMI)
    
    Parameters:
        weight_kg: Weight in kilograms
        height_m: Height in meters
        
    Returns:
        BMI value (float)
    """
    bmi = weight_kg / (height_m ** 2)
    return bmi

In [ ]:
bmi = calculate_bmi(70, 1.75)
print(f"\nBMI: {bmi}")

In [ ]:
# Function with Default Parameters
def power(base, exponent=2):
    """Calculate power with default exponent of 2 (square)"""
    return base ** exponent

In [ ]:
print(f"\n5^2 = {power(6)}")
print(f"5^3 = {power(5, 3)}")

In [ ]:
# Function with Multiple Return Values
def analyze_data(numbers):
    """Return statistics for a list of numbers"""
    total = sum(numbers)
    count = len(numbers)
    average = total / count
    minimum = min(numbers)
    maximum = max(numbers)
    return total, average, minimum, maximum



In [ ]:
data = [10, 20, 30, 40, 50]
total, avg, min_val, max_val = analyze_data(data)

print(f"\nData Analysis:")
print(f"Total: {total}, Average: {avg}, Min: {min_val}, Max: {max_val}")

## 4.2 Advanced Function Concepts

In [ ]:
# *args - Variable Number of Arguments
def calculate_average(*numbers):
    """Calculate average of any number of values"""
    if len(numbers) == 0:
        return 0
    return sum(numbers) / len(numbers)

print("Averages:")
print(f"Average of 10, 20: {calculate_average(10, 20)}")
print(f"Average of 10, 20, 30, 40: {calculate_average(10, 20, 30, 40)}")

In [ ]:
# **kwargs - Keyword Arguments
def create_student_profile(**info):
    """Create student profile from keyword arguments"""
    print("\nStudent Profile:")
    for key, value in info.items():
        print(f"  {key.capitalize()}: {value}")

create_student_profile(name="John", age=20, major="Data Science", gpa=3.8)


هنا في اسايمنت بتاع preprocesing


# Week 16 Sesssion 2

In [ ]:
# Lambda Functions (Anonymous Functions)
# Syntax: lambda arguments: expression
square = lambda x: x ** 2
print(f"\nSquare of 5: {square(5)}")

In [ ]:
def squares(x):
    result = x**2
    return result

squares(8)

In [ ]:
# Lambda with map() - Apply function to all items
numbers = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x ** 2, numbers))
print(f"\nOriginal: {numbers}")
print(f"Squared: {squared}")

In [ ]:
def seif (numbers):
    for i in numbers:
        if i % 2 == 0:
            return i

In [ ]:
# Lambda with filter() - Filter items based on condition
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even = list(filter(lambda x: x % 2 == 0, numbers))
print(f"\nAll numbers: {numbers}")
print(f"Even numbers: {even}")

In [ ]:
# Lambda with sorted() - Custom sorting
students = [
    {"name": "Alice", "grade": 85},
    {"name": "Bob", "grade": 92},
    {"name": "Charlie", "grade": 78}
]

sorted_students = sorted(students, key=lambda s: s['grade'], reverse=True)
print("\nStudents sorted by grade:")
for student in sorted_students:
    print(f" {student['name']}: {student['grade']}")

# Week 17 session 1(offline)

# 4.3 Modules and Libraries
Modules are files containing Python code that you can import and use. Libraries are collections of modules.

In [ ]:
# Built-in Modules
import math
import random
import datetime

In [ ]:
help(math) # هنا هتطل كل الدول الرياضيه اللي موجوده في مديول ماث

In [ ]:
math.sqrt(9) #  هنا بقوله من مكتبة الرياضيات هاتلي الجذر التربيعي بتاع الرقم تسعه 

In [ ]:
# طب انا ممكن اسمي المكتبه باختصار بدل ما اكتب الاسم كاملة؟ اه ينفع   و استخدمهاا  ازاي 

In [ ]:
import math as m

In [ ]:
m.sqrt(16)   #   علشان اعرف ازاي استخدم الhelp  حسب بقى الداله اللي عايزها اكتب اسمها لو مش عارف ازاي تتكتب استخدم



##### import tensorflow as ts #خاصه بالديب ليرنينج

### تنزيل المكاتب 

In [ ]:
# اول طريقه   !pip install( مثلا pands)

In [ ]:
!pip install pandas

In [ ]:
# الطريقه الثانيه من anaconda Navigator environment 

##### الطريقة الثالثه من anaconda prompet 
 بس بدل ما تكتب 
pip install  الاسم 
اكتب conda install 

In [ ]:
# Math module
print("=== Math Module ===")
print(f"Pi: {math.pi}")
print(f"Square root of 16: {math.sqrt(16)}")
print(f"5.7 rounded up: {math.ceil(5.7)}")
print(f"5.7 rounded down: {math.floor(5.7)}")

In [ ]:
# Random module تولد ارقام عشوئيه 
print("\n=== Random Module ===")
print(f"Random float [0, 1): {random.random()}")
print(f"Random integer [1, 10]: {random.randint(1, 10)}")
print(f"Random choice from list: {random.choice(['Python', 'R', 'SQL'])}")

numbers = [1, 2, 3, 4, 5]
random.shuffle(numbers)
print(f"Shuffled list: {numbers}")

In [ ]:
programs = ["R", "Python", "SQL"]

pro_lan = input("Enter programming language ")

rand = random.choice(programs)

if pro_lan == rand:
    print("congratolation")
else:
    print("try again")

In [ ]:
# طريقة الدكتور 

In [ ]:
import random
import tkinter 
languages = ['Python', 'R', 'SQL']

while True:
    lang = random.choice(languages)
    print(f"\nRandom choice from list: {lang}")

    user_input = input("Enter a programming language: ").strip()

    if user_input.lower() == lang.lower():
        print("Congratulations")
        break
    else:
        print("Try again")

In [ ]:
# Datetime module
print("\n=== Datetime Module ===")
now = datetime.datetime.now()
print(f"Current date and time: {now}")
print(f"Current year: {now.year}")
print(f"Current month: {now.month}")
print(f"Current day: {now.day}")

In [ ]:
# Different import styles
from math import sqrt, pi  # Import specific functions
print(f"\nUsing imported sqrt: {sqrt(25)}")

import numpy as np  # Import with alias (we'll use this extensively)
# We'll explore NumPy in detail in Module 6

# 6.1 Introduction to NumPy
NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides:

Powerful N-dimensional array object (ndarray)

Broadcasting functions for array operations

Tools for integrating C/C++ and Fortran code

Linear algebra, Fourier transform, and random number capabilities

Much faster than Python lists for numerical operations (vectorized operations)

In [7]:
# Import NumPy
import numpy as np

In [ ]:
# Check version
print(f"NumPy version: {np.__version__}")

## 6.2 Creating NumPy Arrays

In [ ]:
# From Python lists
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print(f"Type: {type(arr1)}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}\n")

In [ ]:
# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2)
print(f"Shape: {arr2.shape}")  # (rows, columns)
print(f"Dimensions: {arr2.ndim}")
print(f"Size (total elements): {arr2.size}\n")

# Week 17 Session 2

In [8]:
import numpy as np

# 1. Full array (2x2, filled with 7)
full_array = np.full((2, 2), 7)
print("--- Full Array (2x2, 7) ---")
print(full_array)

# 2. Identity matrix (4x4)
identity_matrix = np.eye(4)
print("\n--- Identity Matrix (4x4) ---")
print(identity_matrix)

# 3. Zero matrix (3x3)
zeros_matrix = np.zeros((3, 3))
print("\n--- Zeros Matrix (3x3) ---")
print(zeros_matrix)

# 4. Ones matrix (2x3)
ones_matrix = np.ones((2, 3))
print("\n--- Ones Matrix (2x3) ---")
print(ones_matrix)

# 5. Random matrix (2x2)
random_matrix = np.random.rand(2, 2)
print("\n--- Random Matrix (2x2) ---")
print(random_matrix)

# 6. Diagonal matrix (1, 2, 3)
diag_matrix = np.diag([1, 2, 3])
print("\n--- Diagonal Matrix ---")
print(diag_matrix)

# 7. Range/Arange matrix (0 to 8, 3x3)
arange_matrix = np.arange(9).reshape(3, 3)
print("\n--- Arange Matrix (3x3) ---")
print(arange_matrix)

--- Full Array (2x2, 7) ---
[[7 7]
 [7 7]]

--- Identity Matrix (4x4) ---
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

--- Zeros Matrix (3x3) ---
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

--- Ones Matrix (2x3) ---
[[1. 1. 1.]
 [1. 1. 1.]]

--- Random Matrix (2x2) ---
[[0.29748565 0.08690086]
 [0.8876625  0.10290862]]

--- Diagonal Matrix ---
[[1 0 0]
 [0 2 0]
 [0 0 3]]

--- Arange Matrix (3x3) ---
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Range-based arrays
arange_arr = np.arange(0, 10, 2) # Start, stop, step
print("Arange (0 to 10, step 2):", arange_arr)
# ده فيكتور كمن خمس اعمده كل مره خد رقم و اسكيب رقم 

In [ ]:
# linspace وظيفتها تقسم المسافة بين رقمين لعدد محدد من النقط بالتساوي
# يعني هنا قسمنا المسافة من 0 لـ 1 لـ 5 أرقام متوزعين بانتظام
linspace_arr = np.linspace(0, 1, 5) 
print("Linspace (0 to 1, 5 values):", linspace_arr)

In [ ]:
# مثال علي لينسبيس مهم للتوضيح 
linspace_arr = np.linspace(0, 1, 10)  
print("Linspace (0 to 1, 5 values):", linspace_arr)

# 6.3 Array Indexing and Slicing

In [ ]:
# 1D Array Indexing
arr = np.array([10, 20, 30, 40, 50, 60])
print(f"Array: {arr}")
print(f"First element: {arr[0]}")

In [ ]:
print(f"Last element: {arr[-1]}")
print(f"Elements 2-4: {arr[1:4]}")

In [ ]:
print(f"Every other element: {arr[::2]}")

In [ ]:
# 2D Array Indexing
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print(f"\n2D Array:\n{arr2d}")
print(f"\nElement at row 1, col 2: {arr2d[1, 2]}")
print(f"First row: {arr2d[0, :]}")
print(f"Second column: {arr2d[:, 1]}")
print(f"\nSubarray (first 2 rows, first 3 cols):\n{arr2d[:2, :3]}")

In [ ]:
print(f"First row: {arr2d[0, :]}")
print(f"Second column: {arr2d[:, 1]}")
print(f"\nSubarray (first 2 rows, first 3 cols):\n{arr2d[:2, :3]}")

In [ ]:
print(f"First row: {arr2d[0, :]}")

In [ ]:
print(f"Second column: {arr2d[:, 1]}")
print(f"\nSubarray (first 2 rows, first 3 cols):\n{arr2d[:2, :3]}")

In [ ]:
print(f"First row: {arr2d[0, :]}")


print(f"Second column: {arr2d[:, 1]}")

print(f"\nSubarray (first 2 rows, first 3 cols):\n{arr2d[:2, :3]}") # subarray   دي علشان اجيب جزء من وحده و الجزء الثاني من وحده 

In [ ]:
# Boolean Indexing (Masking)    الكود ده مهم جدا جدا لاز تفهمه و تفصصه 
data = np.array([10, 15, 20, 25, 30, 35, 40])
print(f"\nData: {data}")
mask = data > 25  # Boolean array
print(f"Mask (data > 25): {mask}")
print(f"Filtered data: {data[mask]}")  # ده اهم سطر في الكود لانه اختصر كذا نقطه 

In [ ]:
# Multiple conditions
filtered = data[(data > 15) & (data < 35)]  # Use & for AND, | for OR
print(f"Data between 15 and 35: {filtered}")

# 6.4 Array Operations (Vectorization)

NumPy operations are vectorized - they operate on entire arrays without explicit loops, making them much faster!

In [ ]:
# Arithmetic Operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a = {a}")
print(f"b = {b}\n")

print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"b / a = {b / a}")
print(f"a ** 2 = {a ** 2}")

# Scalar Operations
print(f"\na * 10 = {a * 10}")
print(f"a + 100 = {a + 100}")
# Universal Functions (ufuncs)
arr = np.array([1, 4, 9, 16, 25])
print(f"\nArray: {arr}")
print(f"Square root: {np.sqrt(arr)}")
print(f"Exponential: {np.exp([1, 2, 3])}")
print(f"Logarithm: {np.log([1, 10, 100, 1000])}")
# Trigonometric functions
angles = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(angles)  # Convert to radians
print(f"\nAngles (degrees): {angles}")
print(f"Sin values: {np.sin(radians)}")
print(f"Cos values: {np.cos(radians)}")



# 6.5 Statistical Operations

In [10]:
# Sample data - exam scores
scores = np.array([75, 82, 90, 68, 95, 88, 79, 85, 92, 77])

print("Exam Scores:", scores)
print("\n=== Statistical Analysis ===")
print(f"Mean (Average): {np.mean(scores):.2f}")      # المتوسط الحسابي
print(f"Median: {np.median(scores):.2f}")             # الوسيط
print(f"Standard Deviation: {np.std(scores):.2f}")    # الانحراف المعياري
print(f"Variance: {np.var(scores):.2f}")              # التباين
print(f"Minimum: {np.min(scores)}")                   # القيمة الصغرى
print(f"Maximum: {np.max(scores)}")                   # القيمة العظمى
print(f"Range: {np.ptp(scores)}")   # Peak to peak
print(f"Sum: {np.sum(scores)}")


# Percentiles
print(f"\n25th Percentile: {np.percentile(scores, 25):.2f}")
print(f"50th Percentile (Median): {np.percentile(scores, 50):.2f}")
print(f"75th Percentile: {np.percentile(scores, 75):.2f}")
# 2D Array Statistics
data_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(f"\n2D Array:\n{data_2d}")
print(f"\nOverall mean: {np.mean(data_2d)}")
print(f"Mean of each column (axis=0): {np.mean(data_2d, axis=0)}")
print(f"Mean of each row (axis=1): {np.mean(data_2d, axis=1)}")
print(f"Sum of each column: {np.sum(data_2d, axis=0)}")
print(f"Sum of each row: {np.sum(data_2d, axis=1)}")


Exam Scores: [75 82 90 68 95 88 79 85 92 77]

=== Statistical Analysis ===
Mean (Average): 83.10
Median: 83.50
Standard Deviation: 8.03
Variance: 64.49
Minimum: 68
Maximum: 95
Range: 27
Sum: 831

25th Percentile: 77.50
50th Percentile (Median): 83.50
75th Percentile: 89.50

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Overall mean: 5.0
Mean of each column (axis=0): [4. 5. 6.]
Mean of each row (axis=1): [2. 5. 8.]
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]


# هنا بقى خلاص كده و فتحنا اسكربيت جديد نطبق و نشتغل عليه داش بورد